version: "3.8"
# Define services
services:
  dbpostgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
