version: "3.8"
# Define services
services:
  promocode:
    # Configuration for building the docker image for the backend service
    build:
      context: /
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - dbpostgres
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:postgresql://dbpostgres:5432/simpledb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
  dbpostgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    networks:
      - backend
# Volumes
volumes:
  db-data:
networks:
  backend: