kind: Service
apiVersion: v1
metadata:
  name: promocode
  labels:
    app: promocode
spec:
  type: NodePort
  selector:
    app: promocode
  ports:
    - port: 8080
      targetPort: 8080
      name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: promocode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promocode
  template:
    metadata:
      labels:
        app: promocode
        version: v1
    spec:
      containers:
        - name: promocode
          image: promocode
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080